[target.nanosplus]
runner = "speculos -a=1 --model=nanosp"

[build]
target = "nanosplus"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

# By default, heap size is enforced to 8192 bytes.
# Recommended values are [2048, 4096, 8192, 16384, 24576]
# Uncomment the following lines to set the heap size 
#[env]
#HEAP_SIZE = "8192"